/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mountain_and_river_scroll.glb --types --keepmaterials --keepmeshes 
Author: Shahriar Shahrabi (https://sketchfab.com/shahriyarshahrabi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mountain-and-river-scroll-dd37769bdc0148a988535f893d01c551
Title: Mountain And River Scroll
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane001_Material_0: THREE.Mesh
    Plane003_Material001_0: THREE.Mesh
    Accesories_VertexCollor_0: THREE.Mesh
    Accesories_VertexCollor_0_1: THREE.Mesh
    Accesories_VertexCollor_0_2: THREE.Mesh
    Accesories_VertexCollor_0_3: THREE.Mesh
    Accesories_VertexCollor_0_4: THREE.Mesh
    Accesories_VertexCollor_0_5: THREE.Mesh
    Accesories_VertexCollor_0_6: THREE.Mesh
    Outline_VertexCollorBackFace_0: THREE.Mesh
    Outline_VertexCollorBackFace_0_1: THREE.Mesh
    Main_Material002_0: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshBasicMaterial
    ['Material.001']: THREE.MeshBasicMaterial
    VertexCollor: THREE.MeshBasicMaterial
    VertexCollorBackFace: THREE.MeshBasicMaterial
    ['Material.002']: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/mountain_and_river_scroll.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Accesories_VertexCollor_0.geometry} material={materials.VertexCollor} />
          <mesh geometry={nodes.Accesories_VertexCollor_0_1.geometry} material={materials.VertexCollor} />
          <mesh geometry={nodes.Accesories_VertexCollor_0_2.geometry} material={materials.VertexCollor} />
          <mesh geometry={nodes.Accesories_VertexCollor_0_3.geometry} material={materials.VertexCollor} />
          <mesh geometry={nodes.Accesories_VertexCollor_0_4.geometry} material={materials.VertexCollor} />
          <mesh geometry={nodes.Accesories_VertexCollor_0_5.geometry} material={materials.VertexCollor} />
          <mesh geometry={nodes.Accesories_VertexCollor_0_6.geometry} material={materials.VertexCollor} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Outline_VertexCollorBackFace_0.geometry} material={materials.VertexCollorBackFace} />
          <mesh geometry={nodes.Outline_VertexCollorBackFace_0_1.geometry} material={materials.VertexCollorBackFace} />
        </group>
        <mesh geometry={nodes.Plane001_Material_0.geometry} material={materials.Material} position={[-10137.571, 3446.379, 939.938]} rotation={[-1.558, 0, 3.138]} scale={113.239} />
        <mesh geometry={nodes.Plane003_Material001_0.geometry} material={materials['Material.001']} position={[-10016.212, 3757.468, -3755.637]} rotation={[-1.58, 0, Math.PI]} scale={70.807} />
        <mesh geometry={nodes.Main_Material002_0.geometry} material={materials['Material.002']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/mountain_and_river_scroll.glb')
