/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/asian_inspired_door.glb --types 
Author: elisjons (https://sketchfab.com/elisjons)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/asian-inspired-door-597b1056752d4dacaca95de9975c8020
Title: Asian inspired door
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: THREE.Mesh
    defaultMaterial_1: THREE.Mesh
    defaultMaterial_2: THREE.Mesh
    defaultMaterial_3: THREE.Mesh
    defaultMaterial_4: THREE.Mesh
    defaultMaterial_5: THREE.Mesh
    defaultMaterial_6: THREE.Mesh
    defaultMaterial_7: THREE.Mesh
    defaultMaterial_8: THREE.Mesh
    defaultMaterial_9: THREE.Mesh
    defaultMaterial_10: THREE.Mesh
    defaultMaterial_11: THREE.Mesh
    defaultMaterial_12: THREE.Mesh
    defaultMaterial_13: THREE.Mesh
    defaultMaterial_14: THREE.Mesh
    defaultMaterial_15: THREE.Mesh
    defaultMaterial_16: THREE.Mesh
    defaultMaterial_17: THREE.Mesh
    defaultMaterial_18: THREE.Mesh
    defaultMaterial_19: THREE.Mesh
    defaultMaterial_20: THREE.Mesh
    defaultMaterial_21: THREE.Mesh
    defaultMaterial_22: THREE.Mesh
    defaultMaterial_23: THREE.Mesh
    defaultMaterial_24: THREE.Mesh
    defaultMaterial_25: THREE.Mesh
    defaultMaterial_26: THREE.Mesh
    defaultMaterial_27: THREE.Mesh
    defaultMaterial_28: THREE.Mesh
    defaultMaterial_29: THREE.Mesh
    defaultMaterial_30: THREE.Mesh
  }
  materials: {
    glass: THREE.MeshStandardMaterial
    blue: THREE.MeshStandardMaterial
    lambert1: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    yellow: THREE.MeshStandardMaterial
    pink: THREE.MeshStandardMaterial
    green: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/asian_inspired_door.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.glass} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.blue} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.defaultMaterial_6.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.defaultMaterial_7.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.defaultMaterial_8.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.defaultMaterial_9.geometry} material={materials.material} />
          <mesh geometry={nodes.defaultMaterial_10.geometry} material={materials.material} />
          <mesh geometry={nodes.defaultMaterial_11.geometry} material={materials.yellow} />
          <mesh geometry={nodes.defaultMaterial_12.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.defaultMaterial_13.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.defaultMaterial_14.geometry} material={materials.pink} />
          <mesh geometry={nodes.defaultMaterial_15.geometry} material={materials.green} />
          <mesh geometry={nodes.defaultMaterial_16.geometry} material={materials.material} />
          <mesh geometry={nodes.defaultMaterial_17.geometry} material={materials.yellow} />
          <mesh geometry={nodes.defaultMaterial_18.geometry} material={materials.material} />
          <mesh geometry={nodes.defaultMaterial_19.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.defaultMaterial_20.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.defaultMaterial_21.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.defaultMaterial_22.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.defaultMaterial_23.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.defaultMaterial_24.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.defaultMaterial_25.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.defaultMaterial_26.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.defaultMaterial_27.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.defaultMaterial_28.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.defaultMaterial_29.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.defaultMaterial_30.geometry} material={materials.lambert1} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/asian_inspired_door.glb')
